workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        # Add your environment variable groups here
        - ios_credentials
      vars:
        XCODE_WORKSPACE: "ios/pelindoabsensi.xcworkspace"
        XCODE_SCHEME: "pelindoabsensi"
        BUNDLE_ID: "com.pelindo.absensi"
        APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
        APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
        APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
        CERTIFICATE_PRIVATE_KEY: $CERTIFICATE_PRIVATE_KEY
      node: 18.20.2
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install Expo CLI
        script: |
          npm install -g expo-cli eas-cli
      - name: Prebuild iOS native project
        script: |
          npx expo prebuild --platform ios --clean
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Set up provisioning profiles
        script: |
          # Automatic code signing setup via Codemagic
          xcode-project use-profiles
      - name: Build iOS IPA
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config Release \
            --archive-flags "-destination 'generic/platform=iOS'"
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
      # Uncomment to publish to App Store Connect
      # app_store_connect:
      #   api_key: $APP_STORE_CONNECT_PRIVATE_KEY
      #   key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
      #   issuer_id: $APP_STORE_CONNECT_ISSUER_ID
      #   submit_to_testflight: true

  ios-adhoc:
    name: iOS Ad-Hoc Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - ios_credentials
      vars:
        XCODE_WORKSPACE: "ios/pelindoabsensi.xcworkspace"
        XCODE_SCHEME: "pelindoabsensi"
        BUNDLE_ID: "com.pelindo.absensi"
      node: 18.20.2
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: true
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install Expo CLI
        script: |
          npm install -g expo-cli eas-cli
      - name: Prebuild iOS native project
        script: |
          npx expo prebuild --platform ios --clean
      - name: Install CocoaPods dependencies
        script: |
          cd ios && pod install
      - name: Set up provisioning profiles (Ad-Hoc)
        script: |
          xcode-project use-profiles
      - name: Build iOS IPA (Ad-Hoc)
        script: |
          xcode-project build-ipa \
            --workspace "$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME" \
            --config Release \
            --export-options-plist ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true

  ios-expo-eas:
    name: iOS Build via EAS
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      groups:
        - expo_credentials
      vars:
        EXPO_TOKEN: $EXPO_TOKEN
      node: 18.20.2
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'eas-build'
          include: true
          source: true
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli
      - name: Authenticate with Expo
        script: |
          eas login --non-interactive
      - name: Build iOS with EAS
        script: |
          eas build --platform ios --profile preview --non-interactive --wait
      - name: Download IPA
        script: |
          eas build:download --platform ios --latest --output ./build
    artifacts:
      - build/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
